name: Check PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tools/requirements.txt ]; then pip install -r tools/requirements.txt; fi

      - name: Run content linter
        run: |
          ./tools/lint.py

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'

      - name: Trying to build website
        run: hugo
